#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_DIR="$(dirname "$SCRIPT_DIR}")";
cd $PROJECT_DIR

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <word_to_add>"
    exit 1
fi

echo $1 >> wordlist.txt
echo "Added $1 to wordlist!"
script/sort_wordlist