#!/bin/bash

echo ""
echo "*********** Updating all the things! ***********"
echo "________________________________________________"

echo ""
echo ">> 1. Linting!"

echo ""
echo "> Checking for formatting errors..."
poetry run ruff format --check .

echo ""
echo "> Fixing formatting errors..."
poetry run ruff format . 

echo ""
echo "> Checking for linting errors..."
poetry run ruff check --fix --exit-zero . 

echo ""
echo "________________________________________________"
echo ""
echo "** Done! **"
echo ""