#!/usr/bin/env bash
set -x
set -e

cd "$(dirname "$0")/.."

if ! command -v poetry &> /dev/null; then
    echo "Poetry not found, installing..."
    pip install poetry
fi

poetry config virtualenvs.in-project true

FILE=poetry.lock
if test -f "$FILE"; then
    echo "$FILE exists, commencing sync!"
    poetry install --sync
else
    echo "$FILE does not exist, installing from pyproject.toml!"
    poetry install --no-root
fi
